### ISSUE TITLE
Some  Suggestions for the Unify AI Tool YAMLs 😊

### ISSUE THREAD

**Issue by KatoStevenMubiru** [Kacper-W-Kozdon/promptflow_unify_integration#5]
Lastly i was looking at the `YAML` files for the **UnifyAI** tools, and I had a few ideas that might help:

**Here are my thoughts 🤔**:

- `evaluate_llm_tool.yaml:`
 It seems like the `prompt_set` input isn't actually used in the `benchmark_models` function. Maybe we could remove that from the YAML to avoid any confusion?[Or not]
- It might also be helpful to add a category (like "LLM Evaluation") and a slightly more detailed description to give users more context.
- `optimize_llm_tool.yaml` and `single_sign_on_tool.yaml:`
 For the connection, config, and secrets inputs, it would be awesome if we could provide a bit more information about their structure and what kind of values they expect. This would make it super clear how to use these tools.
And just like the evaluate_llm_tool.yaml, adding a category and a more informative description would be really helpful!

**Other possible Ideas 💡**:

- Schema Validation: Do you happen to know if PromptFlow has a schema for these YAML files? If so, we could use a validation tool to make sure everything is structured correctly.
- Consistency: It would be great to ensure all the YAML files have the same formatting (indentation, spacing, etc.) just to keep things neat and tidy.
 Here's an example of how we could improve `evaluate_llm_tool.yaml:`

```Yaml
unify_llm_tool.tools.evaluate_llm_tool.benchmark_models:
  name: Unify Benchmark
  type: python
  function: benchmark_models
  category: LLM Evaluation
  description: "Evaluates the performance of different LLM models by retrieving their benchmark data from Unify AI. The tool returns a dictionary of benchmark results for each model."
  inputs:
    models:
      type:
        - list
      description: "A list of model names or endpoints to evaluate."
  module: unify_llm_tool.tools.evaluate_llm_tool
```

What do you think about these suggestions? I'm happy to help with any of the updates if you'd like! 😊

NB: Some of these may even look better In a README file.

**Comment by Kacper-W-Kozdon** [comment]
> Lastly i was looking at the `YAML` files for the **UnifyAI** tools, and I had a few ideas that might help:
> 
> **Here are my thoughts 🤔**:
> 
> * `evaluate_llm_tool.yaml:`
>   It seems like the `prompt_set` input isn't actually used in the `benchmark_models` function. Maybe we could remove that from the YAML to avoid any confusion?[Or not]
> * It might also be helpful to add a category (like "LLM Evaluation") and a slightly more detailed description to give users more context.
> * `optimize_llm_tool.yaml` and `single_sign_on_tool.yaml:`
>   For the connection, config, and secrets inputs, it would be awesome if we could provide a bit more information about their structure and what kind of values they expect. This would make it super clear how to use these tools.
>   And just like the evaluate_llm_tool.yaml, adding a category and a more informative description would be really helpful!
> 
> **Other possible Ideas 💡**:
> 
> * Schema Validation: Do you happen to know if PromptFlow has a schema for these YAML files? If so, we could use a validation tool to make sure everything is structured correctly.
> * Consistency: It would be great to ensure all the YAML files have the same formatting (indentation, spacing, etc.) just to keep things neat and tidy.
>   Here's an example of how we could improve `evaluate_llm_tool.yaml:`
> 
> ```yaml
> unify_llm_tool.tools.evaluate_llm_tool.benchmark_models:
>   name: Unify Benchmark
>   type: python
>   function: benchmark_models
>   category: LLM Evaluation
>   description: "Evaluates the performance of different LLM models by retrieving their benchmark data from Unify AI. The tool returns a dictionary of benchmark results for each model."
>   inputs:
>     models:
>       type:
>         - list
>       description: "A list of model names or endpoints to evaluate."
>   module: unify_llm_tool.tools.evaluate_llm_tool
> ```
> 
> What do you think about these suggestions? I'm happy to help with any of the updates if you'd like! 😊
> 
> NB: Some of these may even look better In a README file.

For the .yaml files I'm following the formatting of the auto-generated blank. Indentation of .yaml files also follows that pattern but I'll double-check. I also have yet to clear out the inconsistencies between the yamls and the python files. I'll check if the addition of the description in the .yaml files is in any way represented in the UI, too- that's what the yamls are used for.

**Comment by KatoStevenMubiru** [comment]
Alright 👍🏾.

**Comment by Kacper-W-Kozdon** [comment]
The changes addressing this particular issue were applied, feel free to check if I haven't missed anything :)

**Comment by Kacper-W-Kozdon** [comment]
> Alright 👍🏾.

The changes addressing this particular issue were applied, feel free to check if I haven't missed anything :)

**Comment by KatoStevenMubiru** [comment]
The YAML files are looking much better with those improved descriptions—great job on that!🫡

One final suggestion: It would be really helpful to explicitly define the structure and expected types for the keys within the `config` and `secrets` dictionaries in the `optimize_llm_tool.yaml` and `single_sign_on_tool.yaml` files. This would make it crystal clear for users on how to correctly configure and use these tools.

For example, you could specify the expected keys and their types like this:

```yaml
config:
  type: Dict[str, Union[str, float]]
  description: |
    A dictionary of configuration parameters:
    - quality_weight: str (default "1")
    - cost_weight: str (default "4.65e-03")
    - time_to_first_token_weight: str (default "2.08e-05")
    - inter_token_latency_weight: str (default "2.07e-03")

secrets:
  type: Dict[str, str]
  description: |
    A dictionary of secret keys:
    - api_key: str (required)
    - endpoint: str (optional)
```

This level of detail will make it much easier for users to understand what’s expected and avoid potential errors.

Thanks again!
